### ISSUE TITLE
Missing key 'zone_status_skip' in dictionary 'xantech8'; returning None

### ISSUE THREAD

**Issue by garageboxnv** [rsnodgrass/hass-xantech#11]
Custom component turns out logging of the following:
`Logger: pyxantech.config
Source: custom_components/xantech/media_player.py:288
Integration: Xantech/Dayton Audio/Sonance Multi-Zone Amps ([documentation](https://github.com/rsnodgrass/hass-xantech))
First occurred: 16:49:32 (2858 occurrences)
Last logged: 17:48:58

Missing key 'zone_status_skip' in dictionary 'xantech8'; returning None`

When restoring snapshot getting following error:
`Logger: pyxantech
Source: custom_components/xantech/media_player.py:375
Integration: Xantech/Dayton Audio/Sonance Multi-Zone Amps ([documentation](https://github.com/rsnodgrass/hass-xantech))
First occurred: 16:50:18 (21 occurrences)
Last logged: 17:50:16

Failed restoring zone 1 command set_volume
Failed restoring zone 1 command set_mute
Failed restoring zone 1 command set_bass
Failed restoring zone 1 command set_balance
Failed restoring zone 1 command set_treble`

**Comment by rsnodgrass** [comment]
Did snapshot save/restore ever work for you in the past?  

I don't think these features were ever finished in this integration...they should probably be removed from the services.yaml until someone implements these in the future.

**Comment by rsnodgrass** [comment]
Moving this to community discussion:
https://community.home-assistant.io/t/xantech-dayton-audio-sonance-multi-zone-amps/450908/5
