### ISSUE TITLE
Home Assistant MediaPlayerDevice is deprecated

### ISSUE THREAD

**Issue by DamianFlynn** [rsnodgrass/hass-xantech#2]
`2021-01-12 11:36:59 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify ZoneMediaPlayer to extend MediaPlayerEntity`

Can you refactor the code to extend `MediaPlayerEntity` ?
thanks

**Comment by DamianFlynn** [comment]
Just changing both class references in the file, and reloading appears to be enough, Trying to test

**Comment by rsnodgrass** [comment]
Can you submit a PR when you have made change?   Thank you!  I can also make the change if that is the only change required.

I wasn't sure if anyone else was using this yet!!!  I'd love to see any automations or other things you've done to put this in practice.

**Comment by DamianFlynn** [comment]
Yep.

I also fixed the other issue. I’ll do a PR tonight

iPhone-iTypo-iAutocorrect-iApologize
Damian
________________________________

**Comment by rsnodgrass** [comment]
Can you submit your PR?  Thanks.
