### ISSUE TITLE
Dax88 Support

### ISSUE THREAD

**Issue by kbrown01** [rsnodgrass/hass-xantech#6]
I did some work on creating support for Dayton Audio Dax88. I am not a developer by any means but you may wish to look at these and integrate into your system. I added a protocol YAML for dayton and a series YAML for dax88
[dayton.yaml.txt](https://github.com/rsnodgrass/hass-xantech/files/9271055/dayton.yaml.txt)
[dax88.yaml.txt](https://github.com/rsnodgrass/hass-xantech/files/9271057/dax88.yaml.txt)
.
Then I have something like this:

- platform: xantech
  type: dax88
  port: /dev/ttyUSB0
  zones:
    11:
      name: "Kitchen"
    12:
      name: "Living Room"
    13:
      name: "Deck"
    14:
      name: "Hot Tub"
    15:
      name: "Patio"
    16:
      name: "Foyer"
    17:
      name: "Master"
    18:
      name: "Unused"
  sources:
    1:
      name: "Alexa"
    2:
      name: "MintyFresh"
    3:
      name: "Volumio"
    4:
      name: "PatioVizio"
    5:
      name: "Input 5"
    6:
      name: "Input 6"
    7:
      name: "Input 7"
    8:
      name: "WiFi"

**Comment by kbrown01** [comment]
Perhaps it would have been better to change things in a different way. Not sure. I am no developer, just a hack but it works like a charm.

**Comment by rsnodgrass** [comment]
Awesome, thank you for the contribution!  

I will add these two files.

**Comment by rsnodgrass** [comment]
Checked these into pyxantech and released new version.
