### ISSUE TITLE
Home Assistant Python 3.10 - pyxantech no longer working

### ISSUE THREAD

**Issue by mrellifant** [rsnodgrass/hass-xantech#7]
Hi,
first up excellent job on this library and hass integration. i've been using it with a xantech mraudio8x8 over IP to a rPI exposing Ser2Net with a usb-2-serial for a while now. worked great (with a minor mod i had to do to support a different baud rate), until, Home Assistant Upgraded their version of Python across the past month or two. I finally sat down to look through the issue properly;

have done some googling and it would appear the source of the issue is that the loop parameter has been deprecated from asyncio library.
some googling of "python 3.10, the *loop* parameter was removed from" - will explain it much better than i can.

I would have tested a bit more on my home assistant machine (supervised on esxi) but not being overly familiar with docker stopped me from trying your pyxantech library on the machine directly itself to test out the necessary code changes first.

but it would seem centered around these two lines in protocol.py (pyxantech); might be able to just remove loop=loop or replace with None.
           self._connected = asyncio.Event(loop=loop)
            self._q = asyncio.Queue(loop=loop)

below is the relevant log entry from home assistant. i'm going to roll back my home assistant core (which i just upgraded to 2022.08.1 back to 2022.06.7) purely for this issue. home audio too important for me

again, thanks so much for your work thus far on such an excellent implementation.
and i would be very appreciative if you could address this issue.
many thanks in advance
Wayne

Logger: homeassistant.components.media_player
Source: custom_components/xantech/media_player.py:131
Integration: Media player (documentation, issues)
First occurred: 4:34:31 PM (1 occurrences)
Last logged: 4:34:31 PM

Error while setting up xantech platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/xantech/media_player.py", line 131, in async_setup_platform
    amp = await async_get_amp_controller(amp_type, port, hass.loop, serial_config_overrides=serial_config)
  File "/usr/local/lib/python3.10/site-packages/pyxantech/__init__.py", line 516, in async_get_amp_controller
    protocol = await async_get_rs232_protocol(port_url, DEVICE_CONFIG[amp_type], serial_config, protocol_config, loop)
  File "/usr/local/lib/python3.10/site-packages/pyxantech/protocol.py", line 143, in async_get_rs232_protocol
    _, protocol = await create_serial_connection(loop, factory, serial_port, **serial_config)
  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 449, in create_serial_connection
    transport, protocol = await connection_for_serial(loop, protocol_factory, serial_instance)
  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 476, in connection_for_serial
    protocol = protocol_factory()
  File "/usr/local/lib/python3.10/site-packages/pyxantech/protocol.py", line 58, in __init__
    self._connected = asyncio.Event(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 168, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary

**Comment by rsnodgrass** [comment]
Thanks @mrellifant for the backtrace and prodding to look into this.  My xantech amp is currently not hooked up (temporarily), so I haven't been using this for a few months.

 I have removed loop=loop from Event call in pyxantech, so 3.10+ users should use version 0.6.6. Those running Python 3.9 or earlier may only be able to use 0.6.5.

**Comment by mrellifant** [comment]
Thanks for that Ryan, most appreciated. 

 

Any chance you could do the same for the line below it,

self._q = asyncio.Queue(loop=loop)

to  

self._q = asyncio.Queue()

and I’ll try that out?

 

If I could figure out how to make python point to a like version I would try that first, but python inside docker is not my strong suit. Many other languages and being outside of docker I would have a chance. I couldn’t figure out how to ssh my way into the container where the code was being run from to test.

 

 

FYI, The home assistant log threw this, identical to before, just a different call

 

Many thanks in advance, Wayne.

 


Logger: homeassistant.components.media_player
Source: custom_components/xantech/media_player.py:131
Integration: Media player (documentation <https://www.home-assistant.io/integrations/media_player> , issues <https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22> )
First occurred: 4:27:55 PM (1 occurrences)
Last logged: 4:27:55 PM

Error while setting up xantech platform for media_player

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform

    await asyncio.shield(task)

  File "/config/custom_components/xantech/media_player.py", line 131, in async_setup_platform

    amp = await async_get_amp_controller(amp_type, port, hass.loop, serial_config_overrides=serial_config)

  File "/usr/local/lib/python3.10/site-packages/pyxantech/__init__.py", line 516, in async_get_amp_controller

    protocol = await async_get_rs232_protocol(port_url, DEVICE_CONFIG[amp_type], serial_config, protocol_config, loop)

  File "/usr/local/lib/python3.10/site-packages/pyxantech/protocol.py", line 143, in async_get_rs232_protocol

    _, protocol = await create_serial_connection(loop, factory, serial_port, **serial_config)

  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 449, in create_serial_connection

    transport, protocol = await connection_for_serial(loop, protocol_factory, serial_instance)

  File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 476, in connection_for_serial

    protocol = protocol_factory()

  File "/usr/local/lib/python3.10/site-packages/pyxantech/protocol.py", line 59, in __init__

    self._q = asyncio.Queue(loop=loop)

  File "/usr/local/lib/python3.10/asyncio/queues.py", line 34, in __init__

    super().__init__(loop=loop)

  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__

    raise TypeError(

TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

**Comment by rsnodgrass** [comment]
If you install the hass-xantech version from 'master' it should pickup this Queue change as well. I did not release a new version yet.

**Comment by mrellifant** [comment]
Thanks for that Ryan,

 

Very close now, the Lovelace mediaplayer UI loads now (where previously would just show unavailable). However anytime you try to click on anything (eg power toggle) a message similar to the following is thrown.

 

I can’t thank you enough for looking into it this far.

 

 

Logger: custom_components.xantech.media_player
Source: custom_components/xantech/media_player.py:302
Integration: Xantech Multi-Zone Amps (documentation <https://github.com/rsnodgrass/hass-xantech> )
First occurred: 6:15:52 PM (473 occurrences)
Last logged: 6:25:58 PM

*	Failed updating Xantech House Audio zone 5 (Study): wait_for() got an unexpected keyword argument 'loop'
*	Failed updating Xantech House Audio zone 6 (Spare Bedroom): wait_for() got an unexpected keyword argument 'loop'
*	Failed updating Xantech House Audio zone 7 (Laundry): wait_for() got an unexpected keyword argument 'loop'
*	Failed updating Xantech House Audio zone 8 (Outside Laundry): wait_for() got an unexpected keyword argument 'loop'
*	Failed updating Xantech House Audio zone 1 (Master Bedroom): wait_for() got an unexpected keyword argument 'loop'

 

I had to make a change to the xantech media_player.py to support a different baudrate, ( that I couldn’t figure out how to put in the configuration.yaml, but, could figure out how to put in the media_player.py file), this would throw out the line number a tiny bit. So I’ve identified which is line 302 from my side below:  but for sure the status= line is the one reporting the issue, but the try catch is reporting it. I couldn’t find wait_for() in the code, suspect its in the pyxantech code. But the async is just reporting it back here.

If you have time to look into it, that would be greatly appreciated, if not, I’ll rollback home assistant for a while.

Also if you have a tip on how to make home assistant flush its pypi cache ( I had to rollback the vm) which im happy to do; to get the change you just made that wasn’t released yet.. updating from master kept the previous version annoyingly. Until I rolled back the vm and then forced it to get a new version.

Kind regards

Wayne.

 

[Media_player.py]

   async def async_update(self):

        """Retrieve the latest state."""

        try:

            LOG.debug(f"Updating {self.zone_info}")

            status = await self._amp.zone_status(self._zone_id)

            if not status:

                return

        except Exception as e:

            # log up to two times within a specific period to avoid saturating the logs

            @limits(calls=2, period=10*MINUTES)

            def log_failed_zone_update():

                LOG.warning(f"Failed updating {self.zone_info}: %s", e)

            log_failed_zone_update()    <== LINE 302

            return

**Comment by mrellifant** [comment]
Hi Ryan,

 

I spent some time going through it tonight, and managed to get it working :) After Figured out how to place a local copy of pyxantech on the home assistant machine and import from local, if/when you update it and push a new version I’ll use/test that again in the future.

 

The additional modifications required are as follows , namely, to remove loop=self_loop from two locations in Pyxantech\protocol.py

 

SNIPPET 1 around line 80

 

 

        def data_received(self, data):

#            LOG.debug(f"Received from {self._serial_port}: {data}")

#WBC         asyncio.ensure_future(self._q.put(data), loop=self._loop)   <REMOVE loop=self._loop

            asyncio.ensure_future(self._q.put(data))

 

 

SNIPPET 2 around line 116

 

            # read the response

            data = bytearray()

            response_eol = self._protocol_config[CONF_RESPONSE_EOL].encode('ascii')

            try:

                while True:

                    data += await asyncio.wait_for(self._q.get(), self._timeout)                     

#WBC                data += await asyncio.wait_for(self._q.get(), self._timeout, loop=self._loop) <REMOVE loop=self._loop

 

Works great again!

 

Thanks heaps, for your efforts putting this together!

**Comment by rsnodgrass** [comment]
@mrellifant if you use the 'master' version of hass-xantech it should now pull in pyxantech 0.6.8 which includes these changes.
