### ISSUE TITLE
Removed Exception for UnicodeDecodeError

### ISSUE THREAD

**Issue by kbrown01** [rsnodgrass/hass-xantech#9]
While I have not fully tested this ... only debug logs ... I believe the test for skipping on a UnicodeDecodeError was removed. On my Daxx88 install, i get errors changing volumes and such thrown to the HA log.

I see this in my code differencing I see this was removed from protocol.py:

`            except UnicodeDecodeError:
                LOG.info("Hex data returned, skipping")`

As I said, I had  customized version that I just personally made, but I am pretty sure I did not write that originally. Anyway, I my HA logs set to debug show this:

`2022-08-14 14:18:38.813 ERROR (MainThread) [homeassistant.components.script.stop_music] Stop Music: Error executing script. Unexpected error for call_service at pos 1: 'ascii' codec can't decode byte 0x82 in position 8: ordinal not in range(128)
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
await getattr(self, handler)()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
await service_task
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1713, in async_call
task.result()
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 676, in entity_service_call
future.result() # pop exception if have
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 713, in _handle_entity_call
await result
File "/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 405, in async_turn_off
await self._amp.set_power(self._zone_id, False)
File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/__init__.py", line 408, in wrapper
return (await coro(*args, **kwargs))
File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/__init__.py", line 459, in set_power
await self._protocol.send(_set_power_cmd(self._amp_type, zone, power))
File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/protocol.py", line 28, in wrapper
return await method(self, *method_args, **method_kwargs)
File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/protocol.py", line 40, in wrapper
return await method(self, *method_args, **method_kwargs)
File "/srv/homeassistant/lib/python3.9/site-packages/pyxantech/protocol.py", line 118, in send
LOG.debug(f"Received: %s (eol={response_eol})", bytes(data).decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 8: ordinal not in range(128)`

Just based on the line numbers and such, I would think non-ascii data returned should just through a skip condition. I would note that it normally works, but throws the error also. Except when it is in an automation, because the error causes it to stop.

**Comment by kbrown01** [comment]
I am going to edit the code now and re-insert the Unicode error test and see if that solves the issue.

**Comment by kbrown01** [comment]
I can confirm that all errors go away if the catch is implemented for UnicodeDecodeError

**Comment by garageboxnv** [comment]
@kbrown01 is it possible to share your code for this? I looked into history and can not find the lines you mention.

**Comment by rsnodgrass** [comment]
NOTE: This is happening in a LOG.debug statement, so if you turn down logging can you confirm your integration works?

**Comment by rsnodgrass** [comment]
I also changed the log statement to skip logging the bytes if ascii conversion fails (at least according to the bytes conversion docs).

**Comment by kbrown01** [comment]
I will do that today. I see your point, maybe the logging is the actual error.

**Comment by kbrown01** [comment]
> @kbrown01 is it possible to share your code for this? I looked into history and can not find the lines you mention.

I actually added that in looking through versions. What @rsnodgrass has done in version 0.0.10 is how it should be done IMHO. Once I can download and upgrade I will test and if all works close this.

**Comment by kbrown01** [comment]
OK download now works. 

Now the next hurdle. As I have Core installation I guess I must go to python 3.10. Was trying to avoid that nightmare as everything I had was working on 3.9. I guess this requires 3.10 so I need to bite the bullet.

**Comment by kbrown01** [comment]
OK, upgraded. However the error persists (albiet the logging is skipped):

  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/media_player/__init__.py", line 890, in async_toggle
    await self.async_turn_on()
  File "/home/homeassistant/.homeassistant/custom_components/xantech/media_player.py", line 397, in async_turn_on
    await self._amp.set_power(self._zone_id, True)
  File "/srv/homeassistant/lib/python3.10/site-packages/pyxantech/__init__.py", line 408, in wrapper
    return (await coro(*args, **kwargs))
  File "/srv/homeassistant/lib/python3.10/site-packages/pyxantech/__init__.py", line 459, in set_power
    await self._protocol.send(_set_power_cmd(self._amp_type, zone, power))
  File "/srv/homeassistant/lib/python3.10/site-packages/pyxantech/protocol.py", line 28, in wrapper
    return await method(self, *method_args, **method_kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/pyxantech/protocol.py", line 40, in wrapper
    return await method(self, *method_args, **method_kwargs)
  File "/srv/homeassistant/lib/python3.10/site-packages/pyxantech/protocol.py", line 130, in send
    result = result_lines[0].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 8: ordinal not in range(128)

As you can see, the error is now in line 130:

`result = result_lines[0].decode('ascii')`

Even though the logging is skipped, the error is thrown on attempting to decode the result

**Comment by kbrown01** [comment]
I have confirmed that changing that line to:

`result = result_lines[0].decode('ascii', errors='ignore')`

Removes all the issues I am seeing.

**Comment by rsnodgrass** [comment]
This will remove the log error but of course whatever the result is supposed to be of handling the returned data from the amp will be silently ignored and likely won’t work.   
  

  
Not sure what format the returned data is in if not ascii (perhaps utf-8) but that would be important for this to actually work.   
  

  
With errors=ignore everything just silently fails I think.   
  
  
  
  
  
  

  
  
>

**Comment by kbrown01** [comment]
Well, I suppose I could try an get that for you. I looked at it as one way .... meaning the result was meaningless to me ... I say "volume up" it goes up. Because The code has an auto check that grabs the status (state) of all the zones. 

So I have a button like party mode ... it turns volume to 60% in all zones ... I click it and almost immediately the volume goes up. WIthin one second or so, the GUI updates the sliders to the current state of the volume in the zones.

**Comment by kbrown01** [comment]
I went from this guide: https://www.daytonaudio.com/images/resources/300-985-dayton-audio-dax88-user-manual(5).pdf

RS232 Serial Control
Page | 41
The DAX88 can be controlled by many home and commercial automation systems
through its RS-232 serial port. The RS-232 command list, command structure,
and transmission specifications are detailed below.
Baud Rate: 9600
Data Bits: 8
Stop Bits: 1
Parity: None
Flow Control: None
'CR': Carriage Return (0x0D) is required
Control command structure <xxPPuu'CR'
xx: Zone number
01: Zone1
02: Zone2
03: Zone3
04: Zone4
05: Zone5
06: Zone6
07: Zone7
08: Zone8
uu: indicates a value that the command uses, such as 0-38 for volume control
PP: indicates one of the following control action codes
PR:Power control
PR00:Power off
PR01:Power on
MU:Mute control
MU00:Mute off
MU01:Mute on

**Comment by kbrown01** [comment]
But ... it does work so beautiful:

![image](https://user-images.githubusercontent.com/723363/184977966-33081ba0-7245-43a7-8ea9-618e3f7a9ede.png)

**Comment by kbrown01** [comment]
If you want me to put in a special version (or I can try to write it) that spits out the raw response to log I can do it.

**Comment by rsnodgrass** [comment]
@kbrown01 so awesome!!!  Very nice.  I need to get one of my Xantech's installed again (in the middle of a remodel) so I can have it setup as great as yours.

I have an MRAUDIO8x8, MRC88, and MX88ai. I was never able to get the MX88ai to work...mostly because the connector in the back is not RS232 and requires a custom adapter, unlike earlier Xantechs.

Love the display of how you setup "Party Music" page.

**Comment by rsnodgrass** [comment]
Can I add the photo of your Party Music tab to the main README for the project?

**Comment by kbrown01** [comment]
Of course, you want YAML too?

**Comment by rsnodgrass** [comment]
@kbrown01 that would be awesome to have YAML as well...

Lots of great UI ideas here. The simple volume level presets (you can't always have it "Blowout")

Do you have a single source at all times only for all zones...is that why you have the toggle switches for source?

**Comment by kbrown01** [comment]
Yes you can toggle zones in that view to different sources.  See the popdown on the right here:

![image](https://user-images.githubusercontent.com/723363/184979785-cb188985-f8a6-458d-bcb5-f2313daa9345.png)

**Comment by kbrown01** [comment]
There is a lot of "other" things people would need, but here is the YAML for that entire page:

`button_card_templates:
  group_players:
    group_expand: true
    styles:
      card:
        - height: 80px
    tap_action:
      action: call-service
      service: >-
        [[[ if (entity.state == "on") return "homeassistant.turn_off"; else
        return "homeassistant.turn_on" ]]]
      service_data:
        entity_id: entity
  sound_mode:
    group_expand: true
    styles:
      card:
        - height: 80px
    tap_action:
      action: call-service
      service: media_player.volume_set
      service_data:
        entity_id: entity
        volume_level: '[[[ return variables.level ]]]'
views:
  - title: Home
    type: panel
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: conditional
                    conditions:
                      - entity: input_boolean.spoton
                        state: 'on'
                    card:
                      type: custom:mini-media-player
                      entity: media_player.spotify_kevin_brown
                      artwork: full-cover
                      source: full
                      sound_mode: full
                      hide:
                        volume: true
                        source: true
                        power_state: true
                        icon: true
                        controls: true
                        power: true
                        name: true
                        info: true
                        progress: true
                  - type: conditional
                    conditions:
                      - entity: input_boolean.volumion
                        state: 'on'
                    card:
                      type: iframe
                      url: http://192.168.2.243
                      aspect_ratio: 150%
                  - type: conditional
                    conditions:
                      - entity: input_boolean.lmusicon
                        state: 'on'
                    card:
                      type: iframe
                      url: http://192.168.2.245:8321
                      aspect_ratio: 150%
                  - type: conditional
                    conditions:
                      - entity: input_boolean.pandon
                        state: 'on'
                    card:
                      type: picture-entity
                      show_state: false
                      show_name: false
                      camera_view: auto
                      entity: sensor.lastfm_coverart_mega
                      image: https://demo.home-assistant.io/stub_config/bedroom.png
                      camera_image: camera.pandora_coverart
                  - type: conditional
                    conditions:
                      - entity: input_boolean.mediaextractoron
                        state: 'on'
                    card:
                      type: entities
                      entities:
                        - entity: input_text.media_extractor_url
                          name: Media URL
                          type: custom:text-input-row
                  - type: conditional
                    conditions:
                      - entity: input_boolean.mediaextractoron
                        state: 'on'
                    card:
                      type: custom:mini-media-player
                      hide:
                        volume: true
                        power: true
                      source: full
                      sound_mode: full
                      replace_mute: play_pause
                      info: scroll
                      entity: media_player.dax88_8672
                      artwork: full-cover
              - type: vertical-stack
                cards:
                  - type: vertical-stack
                    cards:
                      - type: conditional
                        conditions:
                          - entity: input_boolean.pandon
                            state: 'off'
                          - entity: input_boolean.spoton
                            state: 'off'
                          - entity: input_boolean.lmusicon
                            state: 'off'
                          - entity: input_boolean.volumion
                            state: 'off'
                          - entity: input_boolean.airplayon
                            state: 'off'
                          - entity: input_boolean.mediaextractoron
                            state: 'off'
                        card:
                          type: markdown
                          content: >-
                            No **Music Source** is selected. Please use the
                            switch to **turn on** a Music Source.
                      - type: conditional
                        conditions:
                          - entity: input_boolean.volumion
                            state: 'on'
                        card:
                          type: custom:mini-media-player
                          entity: media_player.rcvolumio
                          group: true
                          hide:
                            volume: true
                            power: true
                            source: true
                          sound_mode: full
                          replace_mute: play_pause
                          info: scroll
                      - type: conditional
                        conditions:
                          - entity: input_boolean.pandon
                            state: 'on'
                        card:
                          type: custom:mini-media-player
                          entity: media_player.pandora
                          group: true
                          hide:
                            volume: true
                            power: true
                          source: full
                          sound_mode: full
                          replace_mute: play_pause
                          info: scroll
                      - type: conditional
                        conditions:
                          - entity: input_boolean.spoton
                            state: 'on'
                        card:
                          type: custom:mini-media-player
                          entity: media_player.spotify_kevin_brown
                          group: true
                          hide:
                            volume: true
                            power: true
                            source: true
                          sound_mode: full
                          replace_mute: play_pause
                          info: scroll
                  - type: horizontal-stack
                    cards:
                      - type: custom:auto-entities
                        card:
                          type: entities
                          title: Music Sources
                          show_header_toggle: false
                          state_color: true
                        filter:
                          include:
                            - entity_id: '*spoton*'
                              options:
                                icon: mdi:music
                            - entity_id: '*pandon*'
                              options:
                                icon: mdi:music
                            - entity_id: '*volumion*'
                              options:
                                icon: mdi:music
                            - entity_id: '*airplayon*'
                              options:
                                icon: mdi:music
                            - entity_id: '*extractoron*'
                              options:
                                icon: mdi:music
                          exclude: []
                        sort:
                          method: none
                      - type: custom:auto-entities
                        card:
                          type: entities
                          title: Speaker Zones
                          show_header_toggle: false
                          state_color: true
                          group: true
                          hide:
                            play_pause: true
                        filter:
                          include:
                            - entity_id: media_player.xan*
                              options:
                                sourceicon: mdi:music
                                type: custom:mini-media-player
                                group: true
                                hide:
                                  controls: true
                                  icon: true
                                  source: false
                          exclude:
                            - entity_id: media_player.xantech8_xantech_house_audio
                  - type: horizontal-stack
                    title: Speaker Groups
                    cards:
                      - type: custom:button-card
                        template: group_players
                        entity: group.dax_party_mode
                        name: Party
                      - type: custom:button-card
                        template: group_players
                        entity: group.dax_tasting
                        name: Tasting
                      - type: custom:button-card
                        template: group_players
                        entity: group.dax_backyard
                        name: Backyard
                      - type: custom:button-card
                        template: group_players
                        entity: group.dax_outside
                        name: Outside
                      - type: custom:button-card
                        template: group_players
                        entity: group.dax_living
                        name: Living
                  - type: horizontal-stack
                    title: Sound Mode
                    cards:
                      - type: custom:button-card
                        icon: mdi:account-circle
                        variables:
                          level: 0.08
                        template: sound_mode
                        entity: group.dax_party_mode
                        name: Conversation
                      - type: custom:button-card
                        icon: mdi:volume-low
                        variables:
                          level: 0.15
                        template: sound_mode
                        entity: group.dax_party_mode
                        name: Soft
                      - type: custom:button-card
                        icon: mdi:volume-medium
                        variables:
                          level: 0.25
                        template: sound_mode
                        entity: group.dax_party_mode
                        name: Fun
                      - type: custom:button-card
                        icon: mdi:volume-high
                        variables:
                          level: 0.5
                        template: sound_mode
                        entity: group.dax_party_mode
                        name: Dance
                      - type: custom:button-card
                        icon: mdi:fire-circle
                        variables:
                          level: 0.65
                        template: sound_mode
                        entity: group.dax_party_mode
                        name: Blowout
          - type: vertical-stack
            cards:
              - type: conditional
                conditions:
                  - entity: input_boolean.spoton
                    state: 'on'
                card:
                  type: custom:spotify-card
                  spotify_entity: media_player.spotify_kevin_brown
                  account: default
                  always_play_random_song: true
                  grid_show_title: true
                  grid_covers_per_row: '10'
                  hide_warning: true
                  hide_top_header: true
                  limit: 40
                  country_code: us
                  playlist_type: default
                  display_style: grid
                  hide_currently_playing: true`

**Comment by rsnodgrass** [comment]
Cool! I added it to the README

**Comment by rsnodgrass** [comment]
I've been trying to figure out how to show everything to guests at the house to use, and I think this strikes a good balance of making it easier to understand than what I was planning.

**Comment by kbrown01** [comment]
In Pandora mode, I have sensors that retrieve cover art from lastFm. 
In Volumio mode, it displays an iframe to the server.

![image](https://user-images.githubusercontent.com/723363/184981515-2b5d0a7f-cc18-45b0-afc0-061efc12b2cd.png)

**Comment by kbrown01** [comment]
That was designed to serve to PADs. We'll place a few on the walls. We have a few other screens that just quickly mute volume from phone or turn off kitchen when my wife is cooking.

**Comment by kbrown01** [comment]
I will leave to you to decide how you wish to close this. I can put some dev code to intercept messages but ignoring them works for the Dayton (possibly it doesn;t send any meaningful info back).

I have some additional code that grabs bass, treble and balance control. Was thinking about putting that in. I can get the values easily and the API already has the ability to change them. Maybe next ... but in reality that is so rare to do.

**Comment by rsnodgrass** [comment]
If it is working for you, we can close. When I get my Xantech back up and running I'll test on that.

**Comment by kbrown01** [comment]
No problem ... just note that it works for me when I snuff the error (which is not in 0.0.10) with this:

`result = result_lines[0].decode('ascii', errors='ignore')`

**Comment by kbrown01** [comment]
Side note, I did not scroll that page in the screen shots ... if I did you would see (in Spotify) you can just click a playlist, you may want to add that to the Readme.

![image](https://user-images.githubusercontent.com/723363/184985906-7fe41e9e-8e9b-42d6-9e1a-c88e586fc881.png)
